Repository AY2324S1-CS2103T-W13-4/tp, pull requests merged in 2023-10, with the labels that each got.

#98 Add test cases to View Command
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: priority.High

#99 Update Risk Level and test cases
  src/main/java/seedu/address/model/risklevel/RiskLevel.java
  src/main/java/seedu/address/model/risklevel/exceptions/ExceedMaxRiskLevelSizeException.java
  src/main/java/seedu/address/model/util/LimitedHashSet.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/WellNusTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#103 Add Schedule Command
  docs/images/Ui.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/WellNusParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/WellNus.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/resources/view/AppointmentListCard.fxml
  src/main/resources/view/AppointmentListPanel.fxml
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: priority.High

#110 Fix wrong label of appointmentcard
  src/main/java/seedu/address/ui/AppointmentCard.java
Labels: priority.High

#125 Update UI to accommodate resizing
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/css/DarkTheme.css
  src/main/resources/css/Extensions.css
  src/main/resources/css/HelpWindow.css
  src/main/resources/view/AppointmentListCard.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StudentListCard.fxml
Labels: priority.High

#133 Add Section in dev guide
  docs/DeveloperGuide.md
Labels: documentation

#136 Update DG with Note Command
  docs/DeveloperGuide.md
  docs/diagrams/NoteSequenceDiagram.puml
  docs/images/NoteSequenceDiagram.png
Labels: documentation

#135 Add dev-guide for view command
  docs/DeveloperGuide.md
  docs/diagrams/ViewActivityDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/ViewActivityDiagram.png
  docs/images/ViewSequenceDiagram.png
Labels: documentation

#137 Update DG for appointment clash
  docs/DeveloperGuide.md
  docs/diagrams/ClashActivityDiagram.puml
  docs/diagrams/ClashSequenceDiagram.puml
  docs/images/ClashActivityDiagram.png
  docs/images/ClashSequenceDiagram.png
Labels: documentation, priority.High

#146 Fix bug in NoteCommand
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/Note.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/model/student/NoteTest.java
Labels: type.Bug

#151 Update UG with Note Command
  build.gradle
  docs/UserGuide.md
Labels: documentation

#149 Add tag command
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/logic/parser/WellNusParser.java
  src/main/java/seedu/address/model/risklevel/RiskLevel.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/util/LimitedHashSet.java
  src/main/java/seedu/address/storage/JsonAdaptedRiskLevel.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/StudentUtil.java
Labels: type.Task, priority.High
