Repository AY2324S1-CS2103T-W13-4/tp, pull requests merged in 2023-11, with the labels that each got.

#157 Update UG for risk level tagging
  docs/UserGuide.md
Labels: documentation

#154 Update UserGuide with filter feature
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/java/seedu/address/ui/AppointmentListPanel.java
Labels: documentation

#160 Check student for appointment
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/WellNus.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.High

#165 Update links in User Guide
  docs/UserGuide.md
Labels: documentation

#167 Fix bug in Command Summary table
  docs/UserGuide.md
Labels: documentation, type.Bug

#169 Fix links in User Guide
  docs/UserGuide.md
Labels: documentation

#172 Add Edit Command into UG Command Summary
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: documentation

#233 Update Name class and User Guide
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/Name.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/student/NameTest.java
Labels: type.Bug

#235 Fix assigned bugs
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/WellNus.java
  src/main/java/seedu/address/model/risklevel/RiskLevel.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/storage/JsonSerializableWellNus.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
Labels: type.Bug

#237 Update UG
  docs/UserGuide.md
Labels: documentation

#238 Add UG FAQ and images
  docs/UserGuide.md
  docs/images/filterFeature.png
  docs/images/findFeature.png
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: documentation

#239 Update DG diagrams and Darren's PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/team/darrentfy.md
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/appointment/Date.java
  src/main/java/seedu/address/storage/JsonAdaptedRiskLevel.java
Labels: documentation

#243 Update UG
  docs/UserGuide.md
  docs/images/GithubReleasePage.png
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonSerializableWellNus.java
Labels: documentation

#242 Fix multiple risk level storage bug
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonSerializableWellNus.java
Labels: type.Bug

#244 Fix minor formatting in UG
  docs/UserGuide.md
Labels: documentation

#245 Fix edit command
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: type.Bug

#249 Fix Storage Bugs
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
Labels: type.Bug, priority.Medium

#252 Fix note bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StudentNotePanel.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
Labels: type.Enhancement, type.Bug

#253 Remove risk from edit
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
Labels: type.Bug

#246 Make Add Name Case Insensitive
  src/main/java/seedu/address/model/student/Name.java
  src/test/java/seedu/address/model/student/StudentTest.java
Labels: type.Bug

#256 Fix incorrect link in PPP
  docs/team/darrentfy.md
Labels: documentation

#259 Add more PR links
  docs/team/simwperic.md
Labels: type.Task

#260 Update PPP
  docs/team/sheeepen.md
Labels: documentation

#265 Add DG planned enhancements
  docs/DeveloperGuide.md
Labels: documentation

#266 Fix fx-alignment
  src/main/resources/css/DarkTheme.css
Labels: type.Bug

#268 Add DG appendix:effort
  docs/DeveloperGuide.md
Labels: documentation

#274 Update Appendix: Effort in DG
  docs/DeveloperGuide.md
Labels: documentation

#275 Improve UG consistency
  docs/UserGuide.md
Labels: documentation

#276 Fix links in UG
  docs/UserGuide.md
Labels: documentation, type.Bug

#279 Add additional note in UG
  docs/UserGuide.md
Labels: documentation

#281 Minor fixes for UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#283 Update DG WellNusParser
  docs/diagrams/CancelSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/CancelSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
Labels: documentation

#282 Change 'tags' in json files to 'risklevel'
  docs/UserGuide.md
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/test/data/JsonSerializableWellNusTest/appointmentStudentNotFoundWellNus.json
  src/test/data/JsonSerializableWellNusTest/duplicateAppointmentWellNus.json
  src/test/data/JsonSerializableWellNusTest/duplicateStudentWellNus.json
  src/test/data/JsonSerializableWellNusTest/invalidAppointmentWellNus.json
  src/test/data/JsonSerializableWellNusTest/overlapAppointmentWellNus.json
  src/test/data/JsonSerializableWellNusTest/typicalWellNus.json
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: type.Bug

#285 Improve documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#287 Update UG images
  docs/images/Ui.png
  docs/images/filterFeature.png
  docs/images/findFeature.png
Labels: documentation

#288 Fix bullet points in UG
  docs/UserGuide.md
Labels: documentation

#289 Fix inconsistency
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#290 Fix DG
  docs/DeveloperGuide.md
Labels: documentation

#291 Add page breaks in UG
  docs/UserGuide.md
Labels: documentation

#292 Add line breaks
  docs/DeveloperGuide.md
Labels: documentation

#293 Add more page breaks to UG
  docs/UserGuide.md
Labels: documentation

#295 Rearrange items
  docs/DeveloperGuide.md
Labels: documentation

#296 Fix table of contents in UG
  docs/UserGuide.md
Labels: documentation

#297 Fix page break in UG again
  docs/UserGuide.md
Labels: documentation

#298 Add line breaks
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#300 Fix headers in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#301 Update GithubReleasePage
  docs/images/GithubReleasePage.png
Labels: documentation
